<a href="https://colab.research.google.com/github/angelo-chu/python/blob/main/MAX_kline_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import requests
import pandas as pd

In [63]:
API_URL = "https://max-api.maicoin.com/api/v2/k"  # Replace with actual API URL
market = "btcusdt"  # Specify the market (e.g., "ethusdt")
limit = 412
period = 1440  # Set period to 4320 for 1 month
timestamp = 1661798400  # Converted Unix epoch for September 1st, 2022

# Build the query string with parameters
params = {
    "market": market,
    "limit": limit,
    "period": period,
    "timestamp": timestamp,
}

In [64]:
response = requests.get(API_URL, params=params)

In [65]:
if response.status_code == 200:
  # Request successful
  data = pd.DataFrame(response.json())
  print(data)
  # Process the data (array of timestamps, open, high, low, close, volume)
else:
  print(f"Error: API request failed with status code {response.status_code}")

              0         1         2         3         4        5
0    1661817600  20280.98  20538.39  19560.00  19817.02  72.3855
1    1661904000  19823.48  20453.81  19815.58  20038.01  50.6692
2    1661990400  20038.88  20188.61  19602.77  20114.84  59.8277
3    1662076800  20119.19  20398.19  19776.08  19960.53  60.8819
4    1662163200  19960.28  20035.40  19673.56  19833.71  26.2964
..          ...       ...       ...       ...       ...      ...
407  1696982400  27389.01  27470.58  26561.97  26872.25  50.4948
408  1697068800  26870.58  26928.76  26584.59  26745.11   8.8094
409  1697155200  26745.11  27100.00  26700.98  26864.10  22.7642
410  1697241600  26865.17  27009.77  26812.23  26861.97   6.3449
411  1697328000  26864.36  27279.06  26811.01  27151.04   8.8258

[412 rows x 6 columns]

In [66]:
#convert unix epoch to date and time of UTC + 8

from datetime import datetime, timezone, timedelta

In [67]:
def unix_to_utc8(timestamp):
  """Converts a Unix timestamp to a UTC+8 datetime object."""
  # Convert timestamp to datetime object in UTC
  dt = datetime.utcfromtimestamp(timestamp)
  # Convert to UTC+8 timezone
  return dt + timedelta(hours=8)

In [68]:
# Assuming your DataFrame is called 'data' with a column named 'timestamp'
data['datetime_utc8'] = data[0].apply(unix_to_utc8)

In [69]:
data

,0,1,2,3,4,5,datetime_utc8
0,1661817600,20280.98,20538.39,19560.00,19817.02,72.3855,2022-08-30 08:00:00
1,1661904000,19823.48,20453.81,19815.58,20038.01,50.6692,2022-08-31 08:00:00
2,1661990400,20038.88,20188.61,19602.77,20114.84,59.8277,2022-09-01 08:00:00
3,1662076800,20119.19,20398.19,19776.08,19960.53,60.8819,2022-09-02 08:00:00
4,1662163200,19960.28,20035.40,19673.56,19833.71,26.2964,2022-09-03 08:00:00
...,...,...,...,...,...,...,...
407,1696982400,27389.01,27470.58,26561.97,26872.25,50.4948,2023-10-11 08:00:00
408,1697068800,26870.58,26928.76,26584.59,26745.11,8.8094,2023-10-12 08:00:00
409,1697155200,26745.11,27100.00,26700.98,26864.10,22.7642,2023-10-13 08:00:00
410,1697241600,26865.17,27009.77,26812.23,26861.97,6.3449,2023-10-14 08:00:00
411,1697328000,26864.36,27279.06,26811.01,27151.04,8.8258,2023-10-15 08:00:00